# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fecha_pb2 as fecha__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fecha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FechaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SiguienteFecha = channel.unary_unary(
                '/fecha.FechaService/SiguienteFecha',
                request_serializer=fecha__pb2.FechaRequest.SerializeToString,
                response_deserializer=fecha__pb2.FechaResponse.FromString,
                _registered_method=True)
        self.SumaDiasFecha = channel.unary_unary(
                '/fecha.FechaService/SumaDiasFecha',
                request_serializer=fecha__pb2.SumaDiasRequest.SerializeToString,
                response_deserializer=fecha__pb2.FechaResponse.FromString,
                _registered_method=True)


class FechaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SiguienteFecha(self, request, context):
        """Metodo para obtener la fecha siguiente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SumaDiasFecha(self, request, context):
        """Metodo para sumar dias a una fecha
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FechaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SiguienteFecha': grpc.unary_unary_rpc_method_handler(
                    servicer.SiguienteFecha,
                    request_deserializer=fecha__pb2.FechaRequest.FromString,
                    response_serializer=fecha__pb2.FechaResponse.SerializeToString,
            ),
            'SumaDiasFecha': grpc.unary_unary_rpc_method_handler(
                    servicer.SumaDiasFecha,
                    request_deserializer=fecha__pb2.SumaDiasRequest.FromString,
                    response_serializer=fecha__pb2.FechaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fecha.FechaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fecha.FechaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FechaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SiguienteFecha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fecha.FechaService/SiguienteFecha',
            fecha__pb2.FechaRequest.SerializeToString,
            fecha__pb2.FechaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SumaDiasFecha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fecha.FechaService/SumaDiasFecha',
            fecha__pb2.SumaDiasRequest.SerializeToString,
            fecha__pb2.FechaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
