# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fecha.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'fecha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x65\x63ha.proto\x12\x05\x66\x65\x63ha\"/\n\x05\x46\x65\x63ha\x12\x0b\n\x03\x64ia\x18\x01 \x01(\x05\x12\x0b\n\x03mes\x18\x02 \x01(\x05\x12\x0c\n\x04\x61nio\x18\x03 \x01(\x05\"+\n\x0c\x46\x65\x63haRequest\x12\x1b\n\x05\x66\x65\x63ha\x18\x01 \x01(\x0b\x32\x0c.fecha.Fecha\"<\n\x0fSumaDiasRequest\x12\x1b\n\x05\x66\x65\x63ha\x18\x01 \x01(\x0b\x32\x0c.fecha.Fecha\x12\x0c\n\x04\x64ias\x18\x02 \x01(\x05\",\n\rFechaResponse\x12\x1b\n\x05\x66\x65\x63ha\x18\x01 \x01(\x0b\x32\x0c.fecha.Fecha2\x8a\x01\n\x0c\x46\x65\x63haService\x12;\n\x0eSiguienteFecha\x12\x13.fecha.FechaRequest\x1a\x14.fecha.FechaResponse\x12=\n\rSumaDiasFecha\x12\x16.fecha.SumaDiasRequest\x1a\x14.fecha.FechaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fecha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FECHA']._serialized_start=22
  _globals['_FECHA']._serialized_end=69
  _globals['_FECHAREQUEST']._serialized_start=71
  _globals['_FECHAREQUEST']._serialized_end=114
  _globals['_SUMADIASREQUEST']._serialized_start=116
  _globals['_SUMADIASREQUEST']._serialized_end=176
  _globals['_FECHARESPONSE']._serialized_start=178
  _globals['_FECHARESPONSE']._serialized_end=222
  _globals['_FECHASERVICE']._serialized_start=225
  _globals['_FECHASERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
