# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tiro.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tiro.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntiro.proto\x12\x04tiro\"\x0f\n\rCentroRequest\"#\n\x0e\x43\x65ntroResponse\x12\x11\n\tdistancia\x18\x01 \x01(\x02\"D\n\x0e\x44isparoRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x0e\n\x06\x61ngulo\x18\x02 \x01(\x02\x12\x11\n\tvelocidad\x18\x03 \x01(\x02\".\n\x0f\x44isparoResponse\x12\x1b\n\x13\x64istancia_al_centro\x18\x01 \x01(\x02\"\x15\n\x13MejorDisparoRequest\":\n\x14MejorDisparoResponse\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x11\n\tdistancia\x18\x02 \x01(\x02\x32\xd1\x01\n\x0cTiroAlBlanco\x12<\n\x0f\x44imeCentroDiana\x12\x13.tiro.CentroRequest\x1a\x14.tiro.CentroResponse\x12<\n\rDisparaCannon\x12\x14.tiro.DisparoRequest\x1a\x15.tiro.DisparoResponse\x12\x45\n\x0cMejorDisparo\x12\x19.tiro.MejorDisparoRequest\x1a\x1a.tiro.MejorDisparoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tiro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CENTROREQUEST']._serialized_start=20
  _globals['_CENTROREQUEST']._serialized_end=35
  _globals['_CENTRORESPONSE']._serialized_start=37
  _globals['_CENTRORESPONSE']._serialized_end=72
  _globals['_DISPAROREQUEST']._serialized_start=74
  _globals['_DISPAROREQUEST']._serialized_end=142
  _globals['_DISPARORESPONSE']._serialized_start=144
  _globals['_DISPARORESPONSE']._serialized_end=190
  _globals['_MEJORDISPAROREQUEST']._serialized_start=192
  _globals['_MEJORDISPAROREQUEST']._serialized_end=213
  _globals['_MEJORDISPARORESPONSE']._serialized_start=215
  _globals['_MEJORDISPARORESPONSE']._serialized_end=273
  _globals['_TIROALBLANCO']._serialized_start=276
  _globals['_TIROALBLANCO']._serialized_end=485
# @@protoc_insertion_point(module_scope)
