# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tiro_pb2 as tiro__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tiro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TiroAlBlancoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DimeCentroDiana = channel.unary_unary(
                '/tiro.TiroAlBlanco/DimeCentroDiana',
                request_serializer=tiro__pb2.CentroRequest.SerializeToString,
                response_deserializer=tiro__pb2.CentroResponse.FromString,
                _registered_method=True)
        self.DisparaCannon = channel.unary_unary(
                '/tiro.TiroAlBlanco/DisparaCannon',
                request_serializer=tiro__pb2.DisparoRequest.SerializeToString,
                response_deserializer=tiro__pb2.DisparoResponse.FromString,
                _registered_method=True)
        self.MejorDisparo = channel.unary_unary(
                '/tiro.TiroAlBlanco/MejorDisparo',
                request_serializer=tiro__pb2.MejorDisparoRequest.SerializeToString,
                response_deserializer=tiro__pb2.MejorDisparoResponse.FromString,
                _registered_method=True)


class TiroAlBlancoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DimeCentroDiana(self, request, context):
        """Método para obtener la distancia al centro de la diana
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisparaCannon(self, request, context):
        """Método para disparar el cañón
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MejorDisparo(self, request, context):
        """Método para obtener el mejor disparo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TiroAlBlancoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DimeCentroDiana': grpc.unary_unary_rpc_method_handler(
                    servicer.DimeCentroDiana,
                    request_deserializer=tiro__pb2.CentroRequest.FromString,
                    response_serializer=tiro__pb2.CentroResponse.SerializeToString,
            ),
            'DisparaCannon': grpc.unary_unary_rpc_method_handler(
                    servicer.DisparaCannon,
                    request_deserializer=tiro__pb2.DisparoRequest.FromString,
                    response_serializer=tiro__pb2.DisparoResponse.SerializeToString,
            ),
            'MejorDisparo': grpc.unary_unary_rpc_method_handler(
                    servicer.MejorDisparo,
                    request_deserializer=tiro__pb2.MejorDisparoRequest.FromString,
                    response_serializer=tiro__pb2.MejorDisparoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tiro.TiroAlBlanco', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tiro.TiroAlBlanco', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TiroAlBlanco(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DimeCentroDiana(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiro.TiroAlBlanco/DimeCentroDiana',
            tiro__pb2.CentroRequest.SerializeToString,
            tiro__pb2.CentroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisparaCannon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiro.TiroAlBlanco/DisparaCannon',
            tiro__pb2.DisparoRequest.SerializeToString,
            tiro__pb2.DisparoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MejorDisparo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tiro.TiroAlBlanco/MejorDisparo',
            tiro__pb2.MejorDisparoRequest.SerializeToString,
            tiro__pb2.MejorDisparoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
